---
node_exporter_docker_version: "1.11.1"
node_exporter_docker_tag: "v{{ node_exporter_docker_version }}"
node_exporter_docker_image: "prom/node-exporter:{{ node_exporter_docker_tag }}"
node_exporter_docker_timezone: "{{ timezone_name | default('UTC') }}"
node_exporter_docker_compose_extra_conf: {}

node_exporter_docker_listen_addr: "0.0.0.0"
node_exporter_docker_listen_port: 9100

node_exporter_docker_config: {}
node_exporter_docker_conf_default:
  log.level: "info"
  collector.filesystem.mount-points-exclude: "^/(dev|proc|run|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)"
