---
postgresql_version: "14"
postgresql_docker_tag: "{{ postgresql_version }}"
postgresql_docker_image: "postgres:{{ postgresql_docker_tag }}"
postgresql_docker_uid: 999
postgresql_docker_gid: 999
postgresql_docker_network: bridge # "bridge" or "host" supported
postgresql_docker_bind_mount_volumes: true
postgresql_docker_timezone: "{{ timezone_name }}"
postgresql_docker_extra_volumes: []
postgresql_data_dir: "{{ postgresql_docker_compose_dir }}/data"

postgresql_listen_addr: "0.0.0.0"
postgresql_listen_port: 5432
postgresql_init_user: "postgres"
postgresql_init_pass: "postgres"
postgresql_init_base: "postgres"

postgresql_extra_users: []
postgresql_conf_dict: {}
postgresql_conf_default:
  max_connections: 100
  shared_buffers: 128MB
  temp_buffers: 8MB
  work_mem: 4MB
  maintenance_work_mem: 64MB
  log_line_prefix: "%m [%p] "
  log_timezone: "Etc/UTC"
  statement_timeout: 0
  idle_in_transaction_session_timeout: 0
  timezone: 'Etc/UTC'
  password_encryption: "scram-sha-256"

postgresql_pg_hba_conf_list:
#    TYPE    DATABASE        USER      ADDRESS         METHOD
  - "local   replication     all                       trust"
  - "local   all             all                       trust"
  - "host    replication     all       127.0.0.1/32    trust"
  - "host    replication     all       ::1/128         trust"
  - "host    all             all       all             {{ postgresql_conf_runtime.password_encryption }}"

postgresql_tls_enabled: false
postgresql_tls_cert_crt: |-
postgresql_tls_cert_key: |-
