---

- name: "Create directory: {{ prometheus_setup_dir }}"
  file:
    path:  "{{ prometheus_setup_dir }}"
    owner: root
    group: root
    mode:  0750
    state: directory
  tags:
    - prometheus
    - mkdir


- name: "Create directory: {{ prometheus_conf_dir }}"
  file:
    path:  "{{ prometheus_conf_dir }}"
    owner: root
    group: root
    mode:  0755
    state: directory
  tags:
    - prometheus
    - mkdir


- name: "Create directory: {{ prometheus_data_dir }}"
  file:
    path:  "{{ prometheus_data_dir }}"
    owner: "{{ prometheus_docker_uid | string }}"
    group: "{{ prometheus_docker_gid | string }}"
    mode:  0750
    state: directory
  when: prometheus_bind_mount_data_volumes == true
  tags:
    - prometheus
    - mkdir


- name: "Copy file from template: {{ prometheus_setup_dir }}/docker-compose.yml"
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ prometheus_setup_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0600
    force: yes
  tags:
    - prometheus
    - config


- name: "Copy file from template (if not exists): {{ prometheus_conf_dir }}/prometheus.yml"
  template:
    src: "prometheus.yml.j2"
    dest: "{{ prometheus_conf_dir }}/prometheus.yml"
    owner: root
    group: root
    mode: 0644
    force: no
  tags:
    - prometheus
    - config


- name: "docker-compose up: {{ prometheus_setup_dir }}"
  docker_compose:
    project_src: "{{ prometheus_setup_dir }}"
  tags:
    - prometheus
    - startup
