---
# tasks file specific for CentOS distribution systems

- name: "Install packages: ..."
  ansible.builtin.yum:
    name: "{{ item }}"
    # NOTE: latest state for update package from url
    state: latest
  loop:
    - "{{ zabbix_repo_package_url }}"
  tags:
    - zabbix_repo
    - packages


- name: "Update package lists"
  ansible.builtin.shell: |-
    yum clean metadata && yum makecache{{ ' fast' if ansible_distribution_major_version == '7' else '' }}
  changed_when: false
  tags:
    - zabbix_repo
