---

bash_root_color_prompt: True
bash_root_color_code: "1;31"
bash_root_prompt_map:
  true: '[\[\033[01;31m\]\u\[\033[00m\]@\[\033[{{ bash_root_color_code }}m\]\H\[\033[00m\] \[\033[01;34m\]\w\[\033[00m\]]\\$ '
  false: '[\u@\H \w]\\$ '

bash_conf_system_rc_override: {}
bash_conf_system_rc_default:
  HISTCONTROL: ignoreboth
  HISTSIZE: 16384
  HISTFILESIZE: 65536
  HISTTIMEFORMAT: "'%Y%m%d %H%M%S  '"
  alias ll: "'ls -lah'"

bash_conf_system_rc_runtime: "{{ bash_conf_system_rc_default | combine(bash_conf_system_rc_override) }}"
