---
# tasks file specific for RedHat family systems

- name: "Configuring: {{ bash_root_profile }}"
  lineinfile:
    path: "{{ bash_root_profile }}"
    line: "##### Ansible >>> #####"
    owner: root
    group: root
    mode: 0644
  tags:
    - bash
    - config


- name: "Configuring: {{ bash_root_profile }}"
  lineinfile:
    path: "{{ bash_root_profile }}"
    line: "##### <<< Ansible #####"
  tags:
    - bash
    - config


- name: "Configuring: {{ bash_root_profile }}"
  lineinfile:
    path: "{{ bash_root_profile }}"
    regexp: '^export PS1='
    line: |-
      export PS1='\[\e]0;\u@\h: \w\a\]\[\033[01;31m\]\u\[\033[00m\]@\[\033[01;31m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
    insertafter: "^#+ Ansible >>> #+$"
  when:
    - bash_color_prompt
  tags:
    - bash
    - config
