---
# tasks file specific for RedHat family systems

- name: "Ansible opening tag: {{ bash_root_profile }}"
  lineinfile:
    path: "{{ bash_root_profile }}"
    line: "##### Ansible >>> #####"
    owner: root
    group: root
    mode: 0644
  tags:
    - bash
    - config


- name: "Ansible closing tag: {{ bash_root_profile }}"
  lineinfile:
    path: "{{ bash_root_profile }}"
    line: "##### <<< Ansible #####"
  tags:
    - bash
    - config


- name: "Configuring bash: {{ bash_root_profile }}"
  lineinfile:
    path: "{{ bash_root_profile }}"
    regexp: '^export PS1='
    line: |-
      export PS1='{{ bash_root_prompt_map[bash_root_color_prompt] }}'
    insertafter: "^#+ Ansible >>> #+$"
  tags:
    - bash
    - config
