---
nginx_package_name: "nginx"
nginx_service_name: "nginx"

nginx_conf_dir: "/etc/nginx"
nginx_cert_dir: "/etc/ssl/nginx"
nginx_logrotate_conf_file: "/etc/logrotate.d/nginx"

# shared vars ----------------------------------------------------------------------------------------------------------
# nginx_user_name
# nginx_user_group
