---
- name: "Ensure that variable is string"
  ansible.builtin.assert:
    that: lookup('vars', item) | type_debug in ["str", "string", "AnsibleUnicode", "AnsibleUnsafeText", "AnsibleVaultEncryptedUnicode"]
    quiet: true
    fail_msg: "The variable must be a string, but received {{ lookup('vars', item) | type_debug }}"
  loop:
    - grafana_docker_version
    - grafana_docker_tag
    - grafana_docker_image
    - grafana_docker_instance
    - grafana_docker_network
    - grafana_docker_timezone
    - grafana_docker_conf_dir
    - grafana_docker_data_dir
    - grafana_docker_logs_dir
  tags:
    - grafana
    - validate


- name: "Ensure that variable is integer"
  ansible.builtin.assert:
    that: lookup('ansible.builtin.vars', item) | string | regex_search("^[0-9]+$") is not none
    quiet: true
    fail_msg: "The variable must be an integer, but received {{ lookup('vars', item) | type_debug }}"
  loop:
    - grafana_docker_uid
    - grafana_docker_gid
    - grafana_docker_listen_port
  tags:
    - grafana
    - validate


- name: "Ensure that variable is list"
  ansible.builtin.assert:
    that: lookup('vars', item) | type_debug in ["list", "AnsibleSequence"]
    quiet: true
    fail_msg: "The variable must be a list, but received {{ lookup('vars', item) | type_debug }}"
  loop:
    - grafana_docker_extra_volumes
  tags:
    - grafana
    - validate


- name: "Ensure that variable is dict"
  ansible.builtin.assert:
    that: lookup('vars', item) is mapping
    quiet: true
    fail_msg: "The variable must be a dictionary, but received {{ lookup('vars', item) | type_debug }}"
  loop:
    - grafana_docker_compose_extra_conf
    - grafana_docker_environment
    - grafana_docker_env_default
  tags:
    - grafana
    - validate
