---
zabbix_web_nginx_pgsql_version: "7.0"
zabbix_web_nginx_pgsql_docker_tag: "{{ zabbix_web_nginx_pgsql_version }}-alpine-latest"
zabbix_web_nginx_pgsql_docker_image: "zabbix/zabbix-web-nginx-pgsql:{{ zabbix_web_nginx_pgsql_docker_tag }}"
zabbix_web_nginx_pgsql_docker_timezone: "{{ timezone_name }}"

zabbix_web_nginx_pgsql_docker_listen_addr: "0.0.0.0"
zabbix_web_nginx_pgsql_listen_http_port: 8080

zabbix_server_pgsql_docker_environment: {}
zabbix_web_nginx_pgsql_docker_env_default:
  PHP_TZ: "{{ timezone_name }}"
  ZBX_SERVER_NAME: "Zabbix Server"
  DB_SERVER_HOST: "172.17.0.1"
  DB_SERVER_PORT: 5432
  POSTGRES_DB: "zabbix"
  POSTGRES_USER: "zabbix"
  POSTGRES_PASSWORD: "zabbix"
  ZBX_SERVER_HOST: "172.17.0.1"
  ZBX_SERVER_PORT: 10051
