---
- name: "reload php-fpm-docker"
  ansible.builtin.command: |-
    docker exec {{ php_fpm_docker_container_name }} sh -c "{{ php_fpm_reload_cmd }}"
  args:
    chdir: "{{ php_fpm_docker_compose_dir }}"
  when: not r_php_fpm_start_result.changed
