---
postfix_main_conf_file: "/etc/postfix/main.cf"
postfix_smtp_generic_maps_file: "/etc/postfix/generic"
postfix_sasl_password_maps_file: "/etc/postfix/sasl_passwd"
postfix_smtp_header_checks_file: "/etc/postfix/header_checks"
postfix_sender_canonical_maps_file: "/etc/postfix/canonical"
