---

php_fpm_version: "7.4"
php_fpm_docker_tag: "{{ php_fpm_version }}-fpm"
php_fpm_docker_image: "php:{{ php_fpm_docker_tag }}"

php_fpm_tcp_enable: true
php_fpm_ext_port: 9000

# NOTE: Адрес папки с файлами конфигурации php
php_fpm_php_conf_source: "{{ role_path }}/files/{{ php_fpm_version }}/php"

# NOTE: Адрес папки с файлами конфигурации php-fpm
php_fpm_fpm_conf_source: "{{ role_path }}/files/{{ php_fpm_version }}/php-fpm.d"
