---
postgresql_version: "17"
postgresql_docker_tag: "{{ postgresql_version }}"
postgresql_docker_image: "postgres:{{ postgresql_docker_tag }}"
postgresql_docker_build_template: ""
postgresql_docker_instance: "{{ postgresql_major_version }}"
postgresql_docker_uid: 999
postgresql_docker_gid: 999
postgresql_docker_network: bridge # "bridge" or "host" supported
postgresql_docker_timezone: "{{ timezone_name }}"
postgresql_docker_bind_mount_volumes: true
postgresql_docker_conf_dir: "{{ postgresql_docker_compose_dir }}/conf"
postgresql_docker_data_dir: "{{ postgresql_docker_compose_dir }}/data"
postgresql_docker_extra_volumes: []

postgresql_listen_addr: "0.0.0.0"
postgresql_listen_port: 5432
postgresql_bootstrap_user: "postgres"
postgresql_bootstrap_pass: "postgres"
postgresql_bootstrap_base: "postgres"
postgresql_extra_users: []

### postgresql.conf ----------------------------------------------------------------------------------------------------
postgresql_conf_dict: {}
postgresql_conf_default:
  max_connections: 100
  shared_buffers: 128MB
  temp_buffers: 8MB
  work_mem: 4MB
  maintenance_work_mem: 64MB
  dynamic_shared_memory_type: "posix"
  max_wal_size: 1GB
  min_wal_size: 80MB
  log_timezone: "Etc/UTC"
  datestyle: "iso, mdy"
  timezone: "Etc/UTC"
  lc_messages: "en_US.utf8"
  lc_monetary: "en_US.utf8"
  lc_numeric: "en_US.utf8"
  lc_time: "en_US.utf8"
  default_text_search_config: "pg_catalog.english"
  password_encryption: "scram-sha-256"

### pg_hba.conf --------------------------------------------------------------------------------------------------------
postgresql_pg_hba_conf_list:
#   TYPE     DATABASE        USER      ADDRESS         METHOD
  - "local   replication     all                       trust"
  - "local   all             all                       trust"
  - "host    replication     all       127.0.0.1/32    trust"
  - "host    replication     all       ::1/128         trust"
  - "host    all             all       all             {{ postgresql_conf_runtime.password_encryption }}"

### TLS ----------------------------------------------------------------------------------------------------------------
postgresql_tls_enabled: false
postgresql_tls_cert_crt: |-
postgresql_tls_cert_key: |-
