---
- name: "Include OS distribution specific variables"
  ansible.builtin.include_vars: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
  tags:
    - postfix
    - always


- name: "Validate"
  ansible.builtin.include_tasks: "validate.yml"
  tags:
    - postfix
    - validate


- name: "Install"
  ansible.builtin.include_tasks: "install.yml"
  tags:
    - postfix
    - install
