---

- name: "Include OS family specific variables"
  include_vars: "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
  tags:
    - postfix


- name: "Remove packages: {{ postfix_remove_packages | join(' ') }}"
  package:
    name: "{{ postfix_remove_packages }}"
    state: absent
  tags:
    - postfix
    - package


- name: "Install packages: {{ postfix_install_packages | join(' ') }}"
  package:
    name: "{{ postfix_install_packages }}"
    state: present
  tags:
    - postfix
    - package


- name: "Install packages (SASL): {{ postfix_sasl_packages | join(' ') }}"
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ postfix_sasl_packages }}"
  when:
    - postfix_conf_main_runtime.smtp_sasl_auth_enable == "yes"
  tags:
    - postfix
    - package


- name: "Copy files from template: ..."
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0600
    force: yes
  with_items:
      - { dest: "{{ postfix_smtp_generic_maps_file }}", src: "smtp_generic_maps.j2" }
      - { dest: "{{ postfix_sasl_password_maps_file }}", src: "sasl_password_maps.j2" }
      - { dest: "{{ postfix_smtp_header_checks_file }}", src: "smtp_header_checks.j2" }
      - { dest: "{{ postfix_sender_canonical_maps_file }}", src: "sender_canonical_maps.j2" }
  loop_control:
    label: "{{ item.dest }}"
  notify:
    - execute postmap
  tags:
    - postfix
    - config


- name: "Configuring aliases: {{ postfix_aliases_file }}"
  lineinfile:
    path: "{{ postfix_aliases_file }}"
    regexp: '^{{ item.key }}:'
    line: "{{ item.key }}: {{ item.value }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ lookup('dict', postfix_aliases) }}"
  when:
    - item.value
  notify:
    - execute newaliases
  tags:
    - postfix
    - config


### add/edit
- name: "Configuring postfix: {{ postfix_main_conf_file }}"
  lineinfile:
    path: "{{ postfix_main_conf_file }}"
    regexp: '^{{ item.key }}[\s=]'
    line: "{{ item.key }} = {{ item.value }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ lookup('dict', postfix_conf_main_runtime) | rejectattr('value', 'none') | list }}"
  when:
    - item.value
  notify:
    - restart postfix
  tags:
    - postfix
    - config


### remove
- name: "Configuring postfix: {{ postfix_main_conf_file }}"
  lineinfile:
    path: "{{ postfix_main_conf_file }}"
    state: absent
    regexp: '^{{ item.key }}[\s=]'
  with_items:
    - "{{ lookup('dict', postfix_conf_main_runtime) | selectattr('value', 'none') | list }}"
  when:
    - not item.value
  notify:
    - restart postfix
  tags:
    - postfix
    - config


- name: "Service start: {{ postfix_service_name }}"
  service:
    name: "{{ postfix_service_name }}"
    state: started
    enabled: yes
  register: r_postfix_start
  tags:
    - postfix
    - service
