---
# tasks file specific for CentOS distribution systems

- name: "Copy file from template: /etc/yum.repos.d/{{ docker_repo_file_name }}.repo"
  ansible.builtin.template:
    src: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.repo.j2"
    dest: "/etc/yum.repos.d/{{ docker_repo_file_name }}.repo"
    owner: root
    group: root
    mode: '0644'
  tags:
    - docker-repo
    - config


- name: "Update package lists"
  ansible.builtin.shell: |-
     yum clean metadata && yum makecache fast
  changed_when: false
  tags:
    - docker-repo
