---
# tasks file specific for Ubuntu distribution systems

- name: "Install package: gpg"
  ansible.builtin.apt:
    name: "gpg"
    state: present
  tags:
    - docker-repo
    - package


- name: "Shell command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor --yes -o {{ docker_repo_gpg_file }}"
  ansible.builtin.shell: |-
    set -eo pipefail;
    STATE_OLD=$(md5sum "{{ docker_repo_gpg_file }}" 2>/dev/null) || true;
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor --yes -o "{{ docker_repo_gpg_file }}"
    STATE_NEW=$(md5sum "{{ docker_repo_gpg_file }}" 2>/dev/null);
    if [[ ${STATE_NEW} != ${STATE_OLD} ]]; then echo ansible_changed_sign; fi;
  args:
    executable: /bin/bash
  register: r_docker_repo_curl_gpg
  changed_when: "'ansible_changed_sign' in r_docker_repo_curl_gpg.stdout"
  tags:
    - docker-repo
    - config


- name: "Copy file from template: /etc/apt/sources.list.d/{{ docker_repo_file_name }}.list"
  ansible.builtin.template:
    src: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.repo.j2"
    dest: "/etc/apt/sources.list.d/{{ docker_repo_file_name }}.list"
    owner: root
    group: root
    mode: '0644'
  tags:
    - docker-repo
    - config


- name: "Update package lists"
  ansible.builtin.apt:
    update_cache: true
  tags:
    - docker-repo
