---
# vars file specific for CentOS distribution systems

zabbix_repo_package_url: "https://repo.zabbix.com/zabbix/{{ zabbix_repo_version }}/rhel/{{ ansible_distribution_major_version }}/\
                          x86_64/zabbix-release-latest.el{{ ansible_distribution_major_version }}.noarch.rpm"
