---
- name: "Validate"
  ansible.builtin.include_tasks: "validate.yml"
  tags:
    - validate


- name: "Install package: {{ logrotate_package_name }}"
  ansible.builtin.package:
    name: "{{ logrotate_package_name }}"
    state: present
  tags:
    - logrotate
    - packages


- name: "Copy file from template: {{ logrotate_conf_file }}"
  ansible.builtin.template:
    src: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.conf.j2"
    dest: "{{ logrotate_conf_file }}"
    owner: root
    group: root
    mode: '0644'
  tags:
    - logrotate
    - config
