---
docker_ce_repo_gpg_key_src: "https://download.docker.com/linux/ubuntu/gpg"
docker_ce_repo_gpg_key_file: |-
  {%- if ansible_distribution_major_version | int >= 24 -%}
  /etc/apt/keyrings/docker-ce.asc
  {%- else -%}
  /usr/share/keyrings/docker-archive-keyring.asc
  {%- endif -%}
docker_ce_repo_file: "/etc/apt/sources.list.d/docker-ce.list"
