---

- name: "Include OS family specific variables"
  include_vars: "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
  tags:
    - atop


- name: "Install package: {{ atop_package_name }}"
  package:
    name: "{{ atop_package_name }}"
    state: present
  tags:
    - atop
    - packages


- name: "Copy file from template: {{ atop_conf_file }}"
  template:
    src: "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.conf.j2"
    dest: "{{ atop_conf_file }}"
    owner: root
    group: root
    mode: 0640
    force: yes
  notify: restart atop
  tags:
    - atop
    - config


- name: "Configuring cron.d: {{ atop_service_name }}"
  cron:
    cron_file: "{{ atop_service_name }}"
    name: "delete logs"
    minute: "30"
    hour: "03"
    user: root
    job: find {{ atop_logs_dir }}/*_* -maxdepth 0 -type f -mtime +{{ atop_logs_find_mtime_delete }} -delete
  tags:
    - atop
    - cron


- name: "Service start: {{ atop_service_name }}"
  service:
    name: "{{ atop_service_name }}"
    state: started
    enabled: yes
  register: r_atop_start
  tags:
    - atop
    - service
