---
postgresql_docker_major_version: "{{ postgresql_docker_version.split('.') | first }}"
postgresql_docker_compose_dir: "/srv/postgresql-{{ postgresql_docker_instance }}"
postgresql_docker_container_name: "postgresql-{{ postgresql_docker_instance }}"
postgresql_docker_build_dir: "{{ postgresql_docker_compose_dir }}/build"
postgresql_docker_conf_runtime: "{{ postgresql_docker_conf_default | combine(postgresql_docker_config) }}"
