---
postgresql_major_version: "{{ postgresql_version.split('.') | first }}"
postgresql_docker_compose_dir: "/srv/postgresql-{{ postgresql_docker_instance }}"
postgresql_docker_container_name: "postgresql-{{ postgresql_docker_instance }}"
postgresql_docker_build_dir: "{{ postgresql_docker_compose_dir }}/build"
postgresql_conf_runtime: "{{ postgresql_conf_default | combine(postgresql_conf_dict) }}"
