---
- name: "Include OS distribution specific variables"
  include_vars: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
  tags:
    - docker-ce


- name: "Remove packages: {{ docker_remove_packages | join(' ') }}"
  ansible.builtin.package:
    name: "{{ docker_remove_packages }}"
    state: absent
  tags:
    - docker-ce
    - package


- name: "Include OS distribution specific tasks"
  include_tasks: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
  tags:
    - docker-ce


- name: "Create directory: {{ docker_conf_dir }}"
  ansible.builtin.file:
    path: "{{ docker_conf_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - docker-ce
    - config


- name: "Copy file from template: {{ docker_conf_file }}"
  ansible.builtin.template:
    src: "daemon.json.j2"
    dest: "{{ docker_conf_file }}"
    owner: root
    group: root
    mode: '0644'
  notify: restart docker
  tags:
    - docker-ce
    - config


- name: "Copy file from template: /etc/systemd/system/{{ docker_service_name }}.service.d/override.conf"
  ansible.builtin.template:
    src: "service.override.conf.j2"
    dest: "/etc/systemd/system/{{ docker_service_name }}.service.d/override.conf"
    owner: root
    group: root
    mode: '0644'
  when: docker_systemd_env_dict | length > 0
  notify: restart docker
  tags:
    - docker-ce
    - config


- name: "Service start: {{ docker_service_name }}"
  ansible.builtin.service:
    name: "{{ docker_service_name }}"
    state: started
    enabled: true
  register: r_docker_start
  tags:
    - docker-ce
    - service
