---
- name: "Include OS distribution specific variables"
  include_vars: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
  tags:
    - docker-ce


- name: "Remove packages: {{ docker_remove_packages | join(' ') }}"
  ansible.builtin.package:
    name: "{{ docker_remove_packages }}"
    state: absent
  tags:
    - docker-ce
    - package


- name: "Include OS distribution specific tasks"
  include_tasks: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
  tags:
    - docker-ce


- name: "Create directories: ..."
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  with_items:
    - { path: "{{ docker_conf_dir }}" }
    - { path: "{{ docker_systemd_override_dir }}" }
  tags:
    - docker-ce
    - mkdir


- name: "Copy file from template: {{ docker_conf_file }}"
  ansible.builtin.template:
    src: "daemon.json.j2"
    dest: "{{ docker_conf_file }}"
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart docker
  tags:
    - docker-ce
    - config


- name: "Copy file from template: {{ docker_systemd_override_file }}"
  ansible.builtin.template:
    src: "service.override.conf.j2"
    dest: "{{ docker_systemd_override_file }}"
    owner: root
    group: root
    mode: '0644'
  notify:
    - systemd daemon reload
    - restart docker
  tags:
    - docker-ce
    - config


- name: "Service start: {{ docker_service_name }}"
  ansible.builtin.service:
    name: "{{ docker_service_name }}"
    state: started
    enabled: true
  register: r_docker_start
  tags:
    - docker-ce
    - service
