---
- name: "Install package: {{ nano_package_name }}"
  ansible.builtin.package:
    name: "{{ nano_package_name }}"
    state: present
  tags:
    - nano
    - package


- name: "Copy file from template: {{ nano_conf_file }}"
  ansible.builtin.template:
    src: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.nanorc.j2"
    dest: "{{ nano_conf_file }}"
    owner: root
    group: root
    mode: '0644'
  tags:
    - nano
    - config
