---

- name: "Include OS family variables"
  include_vars: "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
  tags:
    - nano


- name: "Install package: {{ nano_package_name }}"
  package:
    name: "{{ nano_package_name }}"
    state: present
  tags:
    - nano
    - package


- name: "Copy file from template: {{ nano_system_rc_file }}"
  template:
    src: "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.nanorc.j2"
    dest: "{{ nano_system_rc_file }}"
    owner: root
    group: root
    mode: 0644
    force: yes
  tags:
    - nano
    - config
