---
zabbix_agent_package_name: "zabbix-agent"
zabbix_agent_service_name: "zabbix-agent"
zabbix_agent_user_name: "zabbix"
zabbix_agent_user_group: "zabbix"

zabbix_agent_conf_dir: "/etc/zabbix"
zabbix_agent_agentscripts_dir: "{{ zabbix_agent_conf_dir }}/agentscripts"
zabbix_agent_logrotate_file: "/etc/logrotate.d/zabbix-agent"
