---
# vars file specific for Ubuntu distribution systems

zabbix_agent_conf_file: "{{ zabbix_agent_conf_dir }}/zabbix_agentd.conf"
zabbix_agent_conf_d_dir: "{{ zabbix_agent_conf_dir }}/zabbix_agentd.conf.d"
zabbix_agent_logs_dir: "/var/log/zabbix-agent"
