---
docker_repo_gpg_key_src: "https://download.docker.com/linux/ubuntu/gpg"
docker_repo_gpg_key_file: "/usr/share/keyrings/docker-archive-keyring.asc"
docker_repo_file: "/etc/apt/sources.list.d/docker-ce.list"
