---
# tasks file specific for CentOS distribution systems

- name: "Install package: {{ zabbix_repo_package_url }}"
  ansible.builtin.yum:
    name: "{{ zabbix_repo_package_url }}"
    # NOTE: latest state for update package
    state: latest
  tags:
    - zabbix-repo
    - package


- name: "Update package lists"
  ansible.builtin.shell: |-
     yum clean metadata && yum makecache fast
  changed_when: false
  tags:
    - zabbix-repo
