---
# tasks file specific for Ubuntu distribution systems

- name: "Install packages: ..."
  ansible.builtin.apt:
    deb: "{{ item }}"
    # NOTE: present state can update package
    state: present
  loop:
    - "{{ zabbix_repo_package_url }}"
  tags:
    - zabbix-repo
    - package


- name: "Update package lists"
  ansible.builtin.apt:
    update_cache: true
  changed_when: false
  tags:
    - zabbix-repo
