---
- name: "systemd daemon reload"
  ansible.builtin.systemd:
    daemon_reload: true

- name: "restart docker"
  ansible.builtin.service:
    name: "{{ docker_service_name }}"
    state: restarted
  when:
    - not r_docker_start.changed
