---
- name: "systemd daemon reload"
  ansible.builtin.systemd:
    daemon_reload: true

- name: "restart docker-ce"
  ansible.builtin.service:
    name: "{{ docker_ce_service_name }}"
    state: restarted
  when:
    - not r_docker_ce_start.changed
