---
# vars file specific for CentOS distribution systems

docker_remove_packages:
  - "docker"
  - "docker-client"
  - "docker-client-latest"
  - "docker-common"
  - "docker-latest"
  - "docker-latest-logrotate"
  - "docker-logrotate"
  - "docker-engine"
