---
docker_ce_remove_packages:
  - "docker"
  - "docker-client"
  - "docker-client-latest"
  - "docker-common"
  - "docker-latest"
  - "docker-latest-logrotate"
  - "docker-logrotate"
  - "docker-engine"

docker_ce_install_packages:
  - "{{ 'docker-ce-' + docker_ce_version if docker_ce_version else 'docker-ce' }}"
  - "docker-compose-plugin"
