---

prometheus_docker_tag: "v2.32.1"
prometheus_docker_image: "prom/prometheus:{{ prometheus_docker_tag }}"
prometheus_docker_network: bridge # "bridge" or "host" supported
prometheus_bind_mount_data_volumes: true
prometheus_port: 9090
prometheus_storage_tsdb_retention_time: "31d"
prometheus_storage_tsdb_retention_size: "0"
# TODO: separate default config and strong
prometheus_config:
  global:
    scrape_interval: 15s
    evaluation_interval: 15s
    scrape_timeout: 12s
  alerting:
    alertmanagers:
      - static_configs:
        - targets: []
  rule_files: []
  scrape_configs:
    - job_name: "prometheus"
      static_configs:
        - targets: ["127.0.0.1:9090"]
