---
- name: "restart postgresql-docker"
  community.docker.docker_compose_v2:
    project_src: "{{ postgresql_docker_compose_dir }}"
    restarted: true
    timeout: 60
  when: not r_postgresql_start_result.changed
