---
zabbix_server_pgsql_version: "6.4"
zabbix_server_pgsql_docker_tag: "{{ zabbix_server_pgsql_version }}-alpine-latest"
zabbix_server_pgsql_docker_image: "zabbix/zabbix-server-pgsql:{{ zabbix_server_pgsql_docker_tag }}"
zabbix_server_pgsql_docker_uid: 1997
zabbix_server_pgsql_docker_gid: 1995
zabbix_server_pgsql_docker_network: bridge # "bridge" or "host" supported
zabbix_server_pgsql_docker_bind_mount_volumes: true
zabbix_server_pgsql_docker_timezone: "{{ timezone_name }}"
zabbix_server_pgsql_docker_extra_volumes: []
zabbix_server_pgsql_export_dir: "{{ zabbix_server_pgsql_docker_compose_dir }}/export"
zabbix_server_pgsql_snmptraps_dir: "{{ zabbix_server_pgsql_docker_compose_dir }}/snmptraps"
zabbix_server_pgsql_alertscripts_src: "{{ role_path }}/files/alertscripts"
zabbix_server_pgsql_externalscripts_src: "{{ role_path }}/files/externalscripts"

zabbix_server_pgsql_listen_addr: "0.0.0.0"
zabbix_server_pgsql_listen_port: 10051
zabbix_server_pgsql_db_host: "172.17.0.1"
zabbix_server_pgsql_db_port: 5432
zabbix_server_pgsql_db_name: "zabbix"
zabbix_server_pgsql_db_user: "zabbix"
zabbix_server_pgsql_db_pass: "zabbix"

zabbix_server_pgsql_docker_env_dict: {}
zabbix_server_pgsql_docker_env_default:
  ZBX_TIMEOUT: 30
  ZBX_TRAPPERTIMEOUT: 30
