---
- name: "Validate"
  ansible.builtin.include_tasks: "validate.yml"
  tags:
    - postgresql
    - validate

- name: "Install"
  ansible.builtin.include_tasks: "install.yml"
  tags:
    - postgresql

- name: "Extra users"
  ansible.builtin.include_tasks: "extra_users.yml"
  when: postgresql_extra_users
  tags:
    - postgresql
