---
- name: "Wait for ready"
  community.postgresql.postgresql_query:
    query: "SELECT 1"
    login_host: "{{ postgresql_listen_addr }}"
    login_port: "{{ postgresql_listen_port }}"
    login_user: "{{ postgresql_init_user }}"
    login_password: "{{ postgresql_init_pass }}"
    login_db: "{{ postgresql_init_base }}"
  register: _result
  until: _result is succeeded
  retries: 60
  delay: 3
