---
- name: "Install packages: ..."
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ zabbix_agent_package_name }}"
  tags:
    - zabbix_agent
    - packages


- name: "Add user '{{ zabbix_agent_user_name }}' to groups: {{ zabbix_agent_user_extra_groups }}"
  ansible.builtin.user:
    name: "{{ zabbix_agent_user_name }}"
    groups: "{{ zabbix_agent_user_extra_groups }}"
    append: true
  notify: restart zabbix-agent
  when: zabbix_agent_user_extra_groups
  tags:
    - zabbix_agent
    - config


- name: "Create directories: ..."
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  loop:
    - { path: "{{ zabbix_agent_conf_dir }}" }
    - { path: "{{ zabbix_agent_conf_d_dir }}", owner: "{{ zabbix_agent_user_name }}", group: "{{ zabbix_agent_user_group }}", mode: '0750' }
    - { path: "{{ zabbix_agent_agentscripts_dir }}", owner: "{{ zabbix_agent_user_name }}", group: "{{ zabbix_agent_user_group }}", mode: '0750' }
    - { path: "{{ zabbix_agent_logs_dir }}", owner: "{{ zabbix_agent_user_name }}", group: "{{ zabbix_agent_user_group }}", mode: '0750' }
  tags:
    - zabbix_agent
    - config


- name: "Copy file from template: {{ zabbix_agent_conf_file }}"
  ansible.builtin.template:
    src: "zabbix_agentd.conf.j2"
    dest: "{{ zabbix_agent_conf_file }}"
    owner: root
    group: "{{ zabbix_agent_user_group }}"
    mode: '0640'
  notify: restart zabbix-agent
  tags:
    - zabbix_agent
    - config


- name: "Copy files: {{ zabbix_agent_conf_d_dir }}/"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ zabbix_agent_conf_d_dir }}/"
    owner: root
    group: "{{ zabbix_agent_user_group }}"
    mode: '0640'
  with_fileglob:
    - "{{ zabbix_agent_conf_d_src }}/*.conf"
  notify: restart zabbix-agent
  tags:
    - zabbix_agent
    - config


- name: "Copy files: {{ zabbix_agent_agentscripts_dir }}/"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ zabbix_agent_agentscripts_dir }}/"
    owner: root
    group: "{{ zabbix_agent_user_group }}"
    mode: '0750'
  with_fileglob:
    - "{{ zabbix_agent_scripts_src }}/*"
  tags:
    - zabbix_agent
    - config


- name: "Copy file from template: {{ zabbix_agent_logrotate_file }}"
  ansible.builtin.template:
    src: "logrotate.d/{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.conf.j2"
    dest: "{{ zabbix_agent_logrotate_file }}"
    owner: root
    group: root
    mode: '0644'
  tags:
    - zabbix_agent
    - config


- name: "SELinux seboolean on: ..."
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: true
    persistent: true
  when: ansible_selinux.status == "enabled"
  loop:
    - "zabbix_can_network"
    - "zabbix_run_sudo"
  tags:
    - zabbix_agent
    - config
    - selinux


- name: "Service start: {{ zabbix_agent_service_name }}"
  ansible.builtin.service:
    name: "{{ zabbix_agent_service_name }}"
    state: started
    enabled: true
  register: r_zabbix_agent_start
  tags:
    - zabbix_agent
    - service
