---
- name: "Install package: {{ nut_package_name }}"
  ansible.builtin.package:
    name: "{{ nut_package_name }}"
    state: present
  tags:
    - nut
    - packages


# BUG: Ubuntu 24.04 nut-2.8.1-3.1ubuntu2
#   $ nut-scanner
#   Cannot load USB library (libusb-1.0.so) : file not found. USB search disabled.
# FIX: Create a symlink or install libusb-1.0-0-dev
- name: "Create symbolic links: ..."
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    state: link
    owner: root
    group: root
  with_items:
    - { src: "libusb-1.0.so.0.4.0", dest: "/usr/lib/x86_64-linux-gnu/libusb-1.0.so" }
  loop_control:
    label: "{{ item.dest }} -> {{ item.src }}"
  tags:
    - nut
    - config


- name: "Copy file from template: {{ nut_conf_file }}"
  ansible.builtin.template:
    src: "nut.conf.j2"
    dest: "{{ nut_conf_file }}"
    owner: root
    group: nut
    mode: '0640'
    force: true
  tags:
    - nut
    - config


- name: "Copy files from template: ..."
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: nut
    mode: '0640'
    force: true
  with_items:
    - { dest: "{{ nut_ups_conf_file }}", src: "ups.conf.j2" }
    - { dest: "{{ nut_upsd_conf_file }}", src: "upsd.conf.j2" }
    - { dest: "{{ nut_upsd_users_file }}", src: "upsd.users.j2" }
  loop_control:
    label: "{{ item.dest }}"
  notify: restart upsd
  tags:
    - nut
    - config


- name: "Copy file from template: {{ nut_upsmon_conf_file }}"
  ansible.builtin.template:
    src: "upsmon.conf.j2"
    dest: "{{ nut_upsmon_conf_file }}"
    owner: root
    group: nut
    mode: '0640'
    force: true
  notify: restart upsmon
  tags:
    - nut
    - config


- name: "Service start: {{ nut_upsd_service_name }}"
  ansible.builtin.service:
    name: "{{ nut_upsd_service_name }}"
    state: started
    enabled: true
  register: r_upsd_start
  tags:
    - nut
    - service


- name: "Service start: {{ nut_upsmon_service_name }}"
  ansible.builtin.service:
    name: "{{ nut_upsmon_service_name }}"
    state: started
    enabled: true
  register: r_upsmon_start
  tags:
    - nut
    - service
