---
- name: "Validate"
  ansible.builtin.include_tasks: "validate.yml"
  tags:
    - wireguard_client
    - validate


- name: "Install package: {{ wireguard_package_name }}"
  ansible.builtin.package:
    name: "{{ wireguard_package_name }}"
    state: present
  tags:
    - wireguard_client
    - packages


- name: "Copy files from template: {{ wireguard_conf_dir }}/"
  ansible.builtin.template:
    src: "tmpl.conf.j2"
    dest: "{{ wireguard_conf_dir }}/wgc{{ index }}.conf"
    owner: root
    group: root
    mode: '0600'
  register: _wireguard_client_copy_config
  notify: restart wireguard client
  loop: "{{ wireguard_client_tunnels }}"
  loop_control:
    index_var: index
    label: "wgc{{ index }}.conf name={{ item.name }}"
  tags:
    - wireguard_client
    - config


- name: "Find unmanaged config files: {{ wireguard_conf_dir }}/wgc*.conf"
  ansible.builtin.find:
    paths: "{{ wireguard_conf_dir }}"
    file_type: file
    patterns: |-
      {%- if wireguard_client_tunnels | length < 10 -%}
      wgc[{{ wireguard_client_tunnels | length }}-9]\.conf
      {%- elif wireguard_client_tunnels | length == 10 -%}
      wgc-not-exists-dummy.conf
      {%- else -%}
      {{ wtf_maximum_supported_number_of_configured_tunnels }}
      {%- endif -%}
    use_regex: true
  register: _result
  tags:
    - wireguard_client
    - config


- name: "Define internal variables"
  ansible.builtin.set_fact:
    _wireguard_client_enabled_indices: |-
      {% set result = [] %}
      {% for x in wireguard_client_tunnels %}
      {% if x.enabled | default(true) %}
      {% set _ = result.append(loop.index0) %}
      {% endif %}
      {% endfor %}
      {{ result | sort }}
    _wireguard_client_disabled_indices: |-
      {% set result = [] %}
      {% for x in wireguard_client_tunnels %}
      {% if not x.enabled | default(true) %}
      {% set _ = result.append(loop.index0) %}
      {% endif %}
      {% endfor %}
      {{ result | sort }}
    _wireguard_client_unmanaged_indices: |-
      {% set result = [] %}
      {% for x in _result.files %}
      {% set _ = result.append(x.path | basename | regex_replace('wgc(\\d)\\.conf', '\\1') | int) %}
      {% endfor %}
      {{ result | sort }}
  tags:
    - wireguard_client
    - config


- name: "Service stop: ..."
  ansible.builtin.service:
    name: "wg-quick@wgc{{ item }}"
    state: stopped
    enabled: false
  loop: "{{ (_wireguard_client_disabled_indices + _wireguard_client_unmanaged_indices) | sort }}"
  loop_control:
    label: "wg-quick@wgc{{ item }}"
  tags:
    - wireguard_client
    - config


- name: "Deleting files: ..."
  ansible.builtin.file:
    path: "{{ wireguard_conf_dir }}/wgc{{ item }}.conf"
    state: absent
  loop: "{{ _wireguard_client_unmanaged_indices }}"
  loop_control:
    label: "wg-quick@wgc{{ item }}"
  tags:
    - wireguard_client
    - config


- name: "Service start: ..."
  ansible.builtin.service:
    name: "wg-quick@wgc{{ index }}"
    state: started
    enabled: true
  register: _wireguard_client_service_start
  when: index in _wireguard_client_enabled_indices
  loop: "{{ wireguard_client_tunnels }}"
  loop_control:
    index_var: index
    label: "wg-quick@wgc{{ index }}"
  tags:
    - wireguard_client
    - service
