---
- name: "Validate"
  ansible.builtin.include_tasks: "validate.yml"
  tags:
    - wireguard_client
    - validate


- name: "Install"
  ansible.builtin.include_tasks: "install.yml"
  tags:
    - wireguard_client
    - install
