---
docker_ce_conf_dir: "/etc/docker"
docker_ce_conf_file: "/etc/docker/daemon.json"

docker_ce_service_name: "docker"
docker_ce_systemd_override_dir: "/etc/systemd/system/{{ docker_ce_service_name }}.service.d"
docker_ce_systemd_override_file: "{{ docker_ce_systemd_override_dir }}/override.conf"

docker_ce_conf_runtime: "{{ docker_ce_conf_default | combine(docker_ce_conf_dict) }}"
