---
zabbix_web_nginx_pgsql_version: "6.0"
zabbix_web_nginx_pgsql_docker_tag: "{{ zabbix_web_nginx_pgsql_version }}-alpine-latest"
zabbix_web_nginx_pgsql_docker_image: "zabbix/zabbix-web-nginx-pgsql:{{ zabbix_web_nginx_pgsql_docker_tag }}"
zabbix_web_nginx_pgsql_docker_timezone: "{{ timezone_name }}"

zabbix_web_nginx_pgsql_listen_addr: "0.0.0.0"
zabbix_web_nginx_pgsql_http_listen_port: 8080
zabbix_web_nginx_pgsql_db_host: "172.17.0.1"
zabbix_web_nginx_pgsql_db_port: 5432
zabbix_web_nginx_pgsql_db_name: "zabbix"
zabbix_web_nginx_pgsql_db_user: "zabbix"
zabbix_web_nginx_pgsql_db_pass: "zabbix"
zabbix_web_nginx_pgsql_zabbix_server_host: "172.17.0.1"
zabbix_web_nginx_pgsql_zabbix_server_port: 10051

zabbix_web_nginx_pgsql_docker_env_dict: {}
zabbix_web_nginx_pgsql_docker_env_default:
  PHP_TZ: "{{ timezone_name }}"
  ZBX_SERVER_NAME: "Zabbix Web"
zabbix_web_nginx_pgsql_docker_env_runtime: "{{ zabbix_web_nginx_pgsql_docker_env_default | combine(zabbix_web_nginx_pgsql_docker_env_dict) }}"
