---
- name: "Install package: {{ screen_package_name }}"
  ansible.builtin.package:
    name: "{{ screen_package_name }}"
    state: present
  tags:
    - screen
    - packages


- name: "Ansible opening tag: {{ screen_system_rc_file }}"
  ansible.builtin.lineinfile:
    path: "{{ screen_system_rc_file }}"
    line: "##### Ansible >>> #####"
    owner: root
    group: root
    mode: '0644'
  tags:
    - screen
    - config


- name: "Ansible closing tag: {{ screen_system_rc_file }}"
  ansible.builtin.lineinfile:
    path: "{{ screen_system_rc_file }}"
    line: "##### <<< Ansible #####"
  tags:
    - screen
    - config


- name: "Configure screen: {{ screen_system_rc_file }}"
  ansible.builtin.lineinfile:
    path: "{{ screen_system_rc_file }}"
    regexp: '^\s*{{ item.key }}\s'
    line: "{{ item.key }} {{ item.value }}"
    insertafter: "^#+ Ansible >>> #+$"
  with_items:
    - "{{ lookup('dict', screen_system_rc_conf_runtime) | rejectattr('value', 'none') | list }}"
  tags:
    - screen
    - config


- name: "Configure screen: {{ screen_system_rc_file }}"
  ansible.builtin.lineinfile:
    path: "{{ screen_system_rc_file }}"
    state: absent
    regexp: '^\s*{{ item.key }}(\s|$)'
  with_items:
    - "{{ lookup('dict', screen_system_rc_conf_runtime) | selectattr('value', 'none') | list }}"
  tags:
    - screen
    - config
