---
- name: "Validate"
  ansible.builtin.include_tasks: "validate.yml"
  tags:
    - php_fpm
    - validate


- name: "Set facts"
  ansible.builtin.include_tasks: "set_facts.yml"
  tags:
    - php_fpm


- name: "Create directories: ..."
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0750') }}"
  when: item.path | length > 1
  with_items:
    - { path: "{{ php_fpm_docker_compose_dir }}", mode: '0750' }
    - { path: "{{ php_fpm_docker_php_conf_dir }}", mode: '0755' }
    - { path: "{{ php_fpm_docker_fpm_conf_dir }}", mode: '0755' }
    - { path: "{{ php_fpm_docker_fpm_sock_dir }}", mode: '0755' }
    - { path: "{{ php_fpm_docker_logs_dir }}", owner: "{{ php_fpm_docker_uid }}", group: "{{ php_fpm_docker_gid }}", mode: '0750' }
    - { path: "{{ php_fpm_docker_sessions_dir }}", owner: "{{ php_fpm_docker_uid }}", group: "{{ php_fpm_docker_gid }}", mode: '0750' }
  tags:
    - php_fpm
    - config


- name: "Copy file from template: {{ php_fpm_docker_compose_dir }}/docker-compose.yml"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ php_fpm_docker_compose_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: '0600'
  tags:
    - php_fpm
    - config


- name: "Copy files (rsync delete): {{ php_fpm_docker_php_conf_dir }}/"
  ansible.posix.synchronize:
    src: "{{ php_fpm_docker_php_conf_src }}/"
    dest: "{{ php_fpm_docker_php_conf_dir }}/"
    archive: false
    times: false
    perms: true
    checksum: true
    links: true
    recursive: true
    delete: true
    rsync_opts:
      - "--chown=root:root"
      - "--chmod=D0755,F0644"
      - "--exclude=.*"
  notify: reload php-fpm-docker
  tags:
    - php_fpm
    - config


- name: "Copy files (rsync delete): {{ php_fpm_docker_fpm_conf_dir }}/"
  ansible.posix.synchronize:
    src: "{{ php_fpm_docker_fpm_conf_src }}/"
    dest: "{{ php_fpm_docker_fpm_conf_dir }}/"
    archive: false
    times: false
    perms: true
    checksum: true
    links: true
    recursive: true
    delete: true
    rsync_opts:
      - "--chown=root:root"
      - "--chmod=D0755,F0644"
      - "--exclude=.*"
  notify: reload php-fpm-docker
  tags:
    - php_fpm
    - config


- name: "Copy file from template: {{ php_fpm_logrotate_conf_file }}"
  ansible.builtin.template:
    src: "logrotate.conf.j2"
    dest: "{{ php_fpm_logrotate_conf_file }}"
    owner: root
    group: root
    mode: '0644'
  tags:
    - php_fpm
    - config


- name: "docker-compose up: {{ php_fpm_docker_compose_dir }}"
  community.docker.docker_compose_v2:
    project_src: "{{ php_fpm_docker_compose_dir }}"
    pull: always
  register: r_php_fpm_docker_start_result
  tags:
    - php_fpm
    - docker-compose


- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers
  tags:
    - php_fpm
