---
- name: "Ensure that variable is dict"
  ansible.builtin.assert:
    that: lookup('vars', item) is mapping
    quiet: true
    fail_msg: "The variable must be a dictionary, but received {{ lookup('vars', item) | type_debug }}"
  loop:
    - dnsmasq_config
  tags:
    - dnsmasq
    - validate


- name: "Ensure that variable is list"
  ansible.builtin.assert:
    that: lookup('vars', item) | type_debug in ["list", "AnsibleSequence"]
    quiet: true
    fail_msg: "The variable must be a list, but received {{ lookup('vars', item) | type_debug }}"
  loop:
    - dnsmasq_dhcp_hosts
    - dnsmasq_blocklist_hosts
    - dnsmasq_blocklist_addresses
  tags:
    - dnsmasq
    - validate


- name: "Ensure that each item in the list is a dictionary"
  ansible.builtin.assert:
    that:
      - lookup('vars', item) | reject('mapping') | length == 0
    quiet: true
    fail_msg: "Each item must be a dictionary"
  loop:
    - dnsmasq_dhcp_hosts
  tags:
    - dnsmasq
    - validate
