---
- name: "Validate"
  ansible.builtin.include_tasks: "validate.yml"
  tags:
    - microsocks
    - validate


- name: "Create directories: ..."
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  loop:
    - { path: "{{ microsocks_docker_compose_dir }}", mode: '0750' }
  when: item.enabled | default(true)
  tags:
    - microsocks
    - install


- name: "Copy file from template: {{ microsocks_docker_compose_dir }}/docker-compose.yml"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ microsocks_docker_compose_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: '0600'
  tags:
    - microsocks
    - install


- name: "docker-compose up: {{ microsocks_docker_compose_dir }}"
  community.docker.docker_compose_v2:
    project_src: "{{ microsocks_docker_compose_dir }}"
    pull: always
  tags:
    - microsocks
    - install
    - startup


- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers
  tags:
    - microsocks
    - install
