---
php_fpm_version: "8.2"
php_fpm_docker_tag: "{{ php_fpm_version }}-fpm"
php_fpm_docker_image: "php:{{ php_fpm_docker_tag }}"
php_fpm_docker_instance: "{{ php_fpm_version.split('.')[0:2] | join('.') }}"
php_fpm_docker_uid: 33
php_fpm_docker_gid: 33
php_fpm_docker_timezone: "{{ timezone_name }}"
php_fpm_docker_extra_volumes: []

php_fpm_docker_php_conf_dir: "{{ php_fpm_docker_compose_dir }}/php"
php_fpm_docker_fpm_conf_dir: "{{ php_fpm_docker_compose_dir }}/php-fpm.d"
php_fpm_docker_fpm_sock_dir: "{{ php_fpm_docker_compose_dir }}/socket"
php_fpm_docker_sessions_dir: "{{ php_fpm_docker_compose_dir }}/sessions"
php_fpm_docker_logs_dir: "{{ php_fpm_docker_compose_dir }}/logs"

php_fpm_docker_php_conf_src: "{{ role_path }}/files/{{ php_fpm_docker_instance }}/php"
php_fpm_docker_fpm_conf_src: "{{ role_path }}/files/{{ php_fpm_docker_instance }}/php-fpm.d"

php_fpm_docker_logrotate_interval: "daily"
php_fpm_docker_logrotate_rotate: 31

php_fpm_docker_tcp_enabled: true
php_fpm_docker_listen_addr: "0.0.0.0"
php_fpm_docker_listen_port: 9000
