---
- name: "Ensure that variable is string"
  ansible.builtin.assert:
    that: lookup('vars', item) | type_debug in ["str", "string", "AnsibleUnicode", "AnsibleUnsafeText", "AnsibleVaultEncryptedUnicode"]
    quiet: true
    fail_msg: "The variable must be a string, but received {{ lookup('vars', item) | type_debug }}"
  loop:
    - node_exporter_docker_version
    - node_exporter_docker_tag
    - node_exporter_docker_image
    - node_exporter_docker_timezone
    - node_exporter_docker_listen_addr
  tags:
    - node_exporter
    - validate


- name: "Ensure that variable is integer"
  ansible.builtin.assert:
    that: lookup('ansible.builtin.vars', item) | string | regex_search("^[0-9]+$") is not none
    quiet: true
    fail_msg: "The variable must be an integer, but received {{ lookup('vars', item) | type_debug }}"
  loop:
    - node_exporter_docker_listen_port
  tags:
    - node_exporter
    - validate


- name: "Ensure that variable is dict"
  ansible.builtin.assert:
    that: lookup('vars', item) is mapping
    quiet: true
    fail_msg: "The variable must be a dictionary, but received {{ lookup('vars', item) | type_debug }}"
  loop:
    - node_exporter_docker_compose_extra_conf
    - node_exporter_docker_config
    - node_exporter_docker_conf_default
  tags:
    - node_exporter
    - validate
