---

- name: "Create directory: {{ postgresql_setup_dir }}"
  file:
    path:  "{{ postgresql_setup_dir }}"
    owner: root
    group: root
    mode:  0750
    state: directory
  tags:
    - postgresql
    - mkdir


- name: "Create directory: {{ postgresql_data_dir }}"
  file:
    path:  "{{ postgresql_data_dir }}"
    owner: "{{ postgresql_docker_uid | string }}"
    group: "{{ postgresql_docker_gid | string }}"
    mode:  0700
    state: directory
  when: postgresql_bind_mount_data_volumes == true
  tags:
    - postgresql
    - mkdir


- name: "Copy file from template: {{ postgresql_setup_dir }}/docker-compose.yml"
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ postgresql_setup_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0600
    force: yes
  tags:
    - postgresql
    - config


- name: "docker-compose up: {{ postgresql_setup_dir }}"
  docker_compose:
    project_src: "{{ postgresql_setup_dir }}"
    pull: yes
  tags:
    - postgresql
    - docker-compose
