---
nginx_version: "1.26"
nginx_docker_tag: "{{ nginx_version }}"
nginx_docker_image: "nginx:{{ nginx_docker_tag }}"
nginx_docker_instance: ""
nginx_docker_uid: 33
nginx_docker_gid: 33
nginx_docker_network: bridge # "bridge" or "host" supported
nginx_docker_timezone: "{{ timezone_name }}"
nginx_docker_cert_dir: "{{ nginx_docker_compose_dir }}/cert"
nginx_docker_conf_dir: "{{ nginx_docker_compose_dir }}/conf"
nginx_docker_data_dir: "{{ nginx_docker_compose_dir }}/data"
nginx_docker_logs_dir: "{{ nginx_docker_compose_dir }}/logs"
nginx_docker_extra_volumes: []
nginx_docker_tmpfs_volumes: []

nginx_docker_cert_src: "{{ role_path }}/files/cert"
nginx_docker_conf_src: "{{ role_path }}/files/conf"
nginx_docker_data_src: "{{ role_path }}/files/data"

nginx_docker_logrotate_interval: "daily"
nginx_docker_logrotate_rotate: 31

nginx_docker_listen_addr: "0.0.0.0"
nginx_docker_listen_port: [80, 443]

### nginx.conf ---------------------------------------------------------------------------------------------------------
nginx_conf_worker_rlimit_nofile: 4096
nginx_conf_worker_connections: 4096
nginx_conf_client_max_body_size: 32m
