---
postgresql_short_version: "{{ postgresql_version.split('.') | first }}"
postgresql_docker_compose_dir: "/srv/postgresql-{{ postgresql_short_version }}"
postgresql_docker_conf_dir: "{{ postgresql_docker_compose_dir }}/conf"
postgresql_docker_container_name: "postgresql-{{ postgresql_short_version }}"

postgresql_conf_runtime: "{{ postgresql_conf_default | combine(postgresql_conf_dict) }}"
