---
- name: "Create directories: ..."
  ansible.builtin.file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  with_items:
    - { path: "{{ zabbix_server_pgsql_setup_dir }}", mode: '0750' }
    - { path: "{{ zabbix_server_pgsql_alertscripts_dir }}" }
    - { path: "{{ zabbix_server_pgsql_externalscripts_dir }}" }
  tags:
    - zabbix-server-pgsql
    - mkdir


- name: "Create directories: ..."
  ansible.builtin.file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  with_items:
    - { path: "{{ zabbix_server_pgsql_export_dir }}", owner: "{{ zabbix_server_pgsql_docker_uid }}", mode: '0750' }
    - { path: "{{ zabbix_server_pgsql_snmptraps_dir }}", owner: "{{ zabbix_server_pgsql_docker_uid }}", mode: '0750' }
  when: zabbix_server_pgsql_docker_bind_mount_volumes
  tags:
    - zabbix-server-pgsql
    - mkdir


- name: "Copy file from template: {{ zabbix_server_pgsql_setup_dir }}/docker-compose.yml"
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ zabbix_server_pgsql_setup_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: '0600'
  tags:
    - zabbix-server-pgsql
    - config


- name: "Copy files: {{ zabbix_server_pgsql_alertscripts_dir }}/"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ zabbix_server_pgsql_alertscripts_dir }}/"
    owner: root
    group: "{{ zabbix_server_pgsql_docker_gid }}"
    mode: '0750'
  with_fileglob:
    - "{{ zabbix_server_pgsql_alertscripts_src }}/*"
  tags:
    - zabbix-server-pgsql
    - config
    - copy


- name: "Copy files: {{ zabbix_server_pgsql_externalscripts_dir }}/"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ zabbix_server_pgsql_externalscripts_dir }}/"
    owner: root
    group: "{{ zabbix_server_pgsql_docker_gid }}"
    mode: '0750'
  with_fileglob:
    - "{{ zabbix_server_pgsql_externalscripts_src }}/*"
  tags:
    - zabbix-server-pgsql
    - config
    - copy


- name: "docker-compose up: {{ zabbix_server_pgsql_setup_dir }}"
  community.docker.docker_compose:
    project_src: "{{ zabbix_server_pgsql_setup_dir }}"
    pull: true
  tags:
    - zabbix-server-pgsql
    - docker-compose
