---
- name: "Wait for ready"
  ansible.builtin.uri:
    url: "{{ _opensearch_docker_base_url }}/_cluster/health?wait_for_status=yellow&timeout=10s"
    method: GET
    validate_certs: false
    follow_redirects: none
    user: "admin"
    password: "{{ opensearch_docker_admin_password }}"
    force_basic_auth: true
    headers:
      Accept: application/json
  register: _opensearch_docker_temp
  failed_when: "_opensearch_docker_temp.status != 200 or _opensearch_docker_temp.json is undefined or \
    (_opensearch_docker_temp.json.status != 'yellow' and _opensearch_docker_temp.json.status != 'green')"
  until: _opensearch_docker_temp is succeeded
  retries: 12
  delay: 5
  tags:
    - opensearch
    - verify
